apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data: # miru a data ni store chestunaru
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: #these labels are deploment labels
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app: shipping
      project: roboshop
      tier: app
  template: #template dhagara nuchi kindha antha pod definition , paina antha deployment
    metadata:
      labels: #these labels are pod labels
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: charankumarpadeti/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
---

#pod to pod communicate avvali ante which service we use clusterIP

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service port we can give anything
    targetPort: 8080 #containerPort  , nginx