apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: #these labels are deployment
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app: rabbitmq
      project: roboshop
      tier: db
  template: #template dhagara nuchi kindha antha pod definition , paina antha deployment
    metadata:
      labels: #these labels are pod labels
        app: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: rabbitmq

---
#pod to pod communicate avvali ante which one we use clusterIP

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: rabbitmq
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 5672 #service port we can give anything
      targetPort: 5672 #containerPort  , nginx


#1. deplyment create avuthundhi, 2. relica create avuthundhi , 3 .pod create avuthundhi , 4. pod velli service ki attach avuthundhi.
