apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data: # miru a data ni store chestunaru
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: #these labels are deployment
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app: mysql
      project: roboshop
      tier: db
  template: #template dhagara nuchi kindha antha pod definition , paina antha deployment
    metadata:
      labels: #these labels are pod labels
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: charankumarpadeti/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql


---
#pod to pod communicate avvali ante which one we use clusterIP

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: mysql
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #service port we can give anything
      targetPort: 3306 #containerPort  , nginx


#1. deplyment create avuthundhi, 2. relica create avuthundhi , 3 .pod create avuthundhi , 4. pod velli service ki attach avuthundhi.
