apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data: # miru a data ni store chestunaru
  MONGO: "true"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: #these labels are deploment labels
    app: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app: user
      project: roboshop
      tier: app
  template: #template dhagara nuchi kindha antha pod definition , paina antha deployment
    metadata:
      labels: #these labels are pod labels
        app: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: charankumarpadeti/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
---

#pod to pod communicate avvali ante which service we use clusterIP

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service port we can give anything
    targetPort: 8080 #containerPort  , nginx